[package]
name = "ukendio/solid"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

include = ["default.project.json", "out", "out/**", "wally.toml"]
exclude = ["**"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"

